#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

py manage.py migrate
export DOCKER_APP_DIRECTORY=/app
/usr/local/bin/gunicorn -c ${DOCKER_APP_DIRECTORY}/config/gunicorn_config.py config.wsgi --chdir=/app