repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.1.0
    hooks:
    - id: isort
      language_version: python3.8
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8