version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: bash /start

  postgres:
    image: local_postgres
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:6.0-alpine